/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const _deepseek_ai_dsh_host_terminal_bridge_terminalUI_close_parameter_0$schema = z.intersection(z.string(), z.unknown())
const _deepseek_ai_dsh_host_terminal_bridge_terminalUI_close_parameter_1$schema = z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'reason': z.string().readonly().optional(),
})
const _deepseek_ai_dsh_host_terminal_bridge_terminalUI_close_result$schema = z.boolean()
const _deepseek_ai_dsh_host_terminal_bridge_terminalUI_open_parameter_0$schema = z.intersection(z.string(), z.unknown())
const _deepseek_ai_dsh_host_terminal_bridge_terminalUI_open_parameter_1$schema = z.union([z.undefined(), z.object({
  'cwd': z.string().readonly().optional(),
  'rows': z.number().readonly().optional(),
  'cols': z.number().readonly().optional(),
})])
const _deepseek_ai_dsh_host_terminal_bridge_terminalUI_open_result$schema = z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'motd': z.string().readonly(),
})
const _deepseek_ai_dsh_host_terminal_bridge_terminalUI_read_parameter_0$schema = z.intersection(z.string(), z.unknown())
const _deepseek_ai_dsh_host_terminal_bridge_terminalUI_read_parameter_1$schema = z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
})
const _deepseek_ai_dsh_host_terminal_bridge_terminalUI_read_result$schema = z.object({
  'text': z.string().readonly(),
  'truncated': z.boolean().readonly(),
  'exited': z.boolean().readonly(),
})
const _deepseek_ai_dsh_host_terminal_bridge_terminalUI_signal_parameter_0$schema = z.intersection(z.string(), z.unknown())
const _deepseek_ai_dsh_host_terminal_bridge_terminalUI_signal_parameter_1$schema = z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'signal': z.union([z.literal("SIGINT"), z.literal("SIGTERM"), z.literal("SIGKILL"), z.literal("SIGTSTP"), z.literal("SIGHUP")]).readonly(),
})
const _deepseek_ai_dsh_host_terminal_bridge_terminalUI_signal_result$schema = z.object({
  'targetPgid': z.number(),
})
const _deepseek_ai_dsh_host_terminal_bridge_terminalUI_write_parameter_0$schema = z.intersection(z.string(), z.unknown())
const _deepseek_ai_dsh_host_terminal_bridge_terminalUI_write_parameter_1$schema = z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'text': z.string().readonly(),
})
const _deepseek_ai_dsh_host_terminal_bridge_terminalUI_write_result$schema = z.void()

export const TYPERT = {
  package: '@deepseek-ai/dsh-host-terminal-bridge',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@deepseek-ai/dsh-host-terminal-bridge#terminalUI/close',
      service: 'terminalUI',
      namespace: 'terminalUI',
      method: 'close',
      invocation: { kind: 'direct' },
      scope: {
        context: 'agent',
        wire: 'agentId',
      },
      parameters: [
        {
          name: 'agent',
          wire: 'agentId',
          source: 'lookup',
          lookup: 'agent',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-session/types#SessionId',
            schema: _deepseek_ai_dsh_host_terminal_bridge_terminalUI_close_parameter_0$schema,
          },
        },
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-host-terminal-bridge/types#TerminalCloseRequest',
            schema: _deepseek_ai_dsh_host_terminal_bridge_terminalUI_close_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-host-terminal-bridge#terminalUI/close:result',
        schema: _deepseek_ai_dsh_host_terminal_bridge_terminalUI_close_result$schema,
      },
      sourceLocation: {"file":"packages/host/terminal-bridge/src/index.ts","line":123,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-host-terminal-bridge#terminalUI/open',
      service: 'terminalUI',
      namespace: 'terminalUI',
      method: 'open',
      invocation: { kind: 'direct' },
      scope: {
        context: 'agent',
        wire: 'agentId',
      },
      parameters: [
        {
          name: 'agent',
          wire: 'agentId',
          source: 'lookup',
          lookup: 'agent',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-session/types#SessionId',
            schema: _deepseek_ai_dsh_host_terminal_bridge_terminalUI_open_parameter_0$schema,
          },
        },
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          acceptsUndefined: true,
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-host-terminal-bridge/types#TerminalOpenRequest',
            schema: _deepseek_ai_dsh_host_terminal_bridge_terminalUI_open_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-host-terminal-bridge/types#TerminalOpenResult',
        schema: _deepseek_ai_dsh_host_terminal_bridge_terminalUI_open_result$schema,
      },
      sourceLocation: {"file":"packages/host/terminal-bridge/src/index.ts","line":50,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-host-terminal-bridge#terminalUI/read',
      service: 'terminalUI',
      namespace: 'terminalUI',
      method: 'read',
      invocation: { kind: 'direct' },
      scope: {
        context: 'agent',
        wire: 'agentId',
      },
      parameters: [
        {
          name: 'agent',
          wire: 'agentId',
          source: 'lookup',
          lookup: 'agent',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-session/types#SessionId',
            schema: _deepseek_ai_dsh_host_terminal_bridge_terminalUI_read_parameter_0$schema,
          },
        },
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-host-terminal-bridge/types#TerminalReadRequest',
            schema: _deepseek_ai_dsh_host_terminal_bridge_terminalUI_read_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-host-terminal-bridge/types#TerminalReadResult',
        schema: _deepseek_ai_dsh_host_terminal_bridge_terminalUI_read_result$schema,
      },
      sourceLocation: {"file":"packages/host/terminal-bridge/src/index.ts","line":84,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-host-terminal-bridge#terminalUI/signal',
      service: 'terminalUI',
      namespace: 'terminalUI',
      method: 'signal',
      invocation: { kind: 'direct' },
      scope: {
        context: 'agent',
        wire: 'agentId',
      },
      parameters: [
        {
          name: 'agent',
          wire: 'agentId',
          source: 'lookup',
          lookup: 'agent',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-session/types#SessionId',
            schema: _deepseek_ai_dsh_host_terminal_bridge_terminalUI_signal_parameter_0$schema,
          },
        },
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-host-terminal-bridge/types#TerminalSignalRequest',
            schema: _deepseek_ai_dsh_host_terminal_bridge_terminalUI_signal_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-host-terminal-bridge#terminalUI/signal:result',
        schema: _deepseek_ai_dsh_host_terminal_bridge_terminalUI_signal_result$schema,
      },
      sourceLocation: {"file":"packages/host/terminal-bridge/src/index.ts","line":111,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-host-terminal-bridge#terminalUI/write',
      service: 'terminalUI',
      namespace: 'terminalUI',
      method: 'write',
      invocation: { kind: 'direct' },
      scope: {
        context: 'agent',
        wire: 'agentId',
      },
      parameters: [
        {
          name: 'agent',
          wire: 'agentId',
          source: 'lookup',
          lookup: 'agent',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-session/types#SessionId',
            schema: _deepseek_ai_dsh_host_terminal_bridge_terminalUI_write_parameter_0$schema,
          },
        },
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-host-terminal-bridge/types#TerminalWriteRequest',
            schema: _deepseek_ai_dsh_host_terminal_bridge_terminalUI_write_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-host-terminal-bridge#terminalUI/write:result',
        schema: _deepseek_ai_dsh_host_terminal_bridge_terminalUI_write_result$schema,
      },
      sourceLocation: {"file":"packages/host/terminal-bridge/src/index.ts","line":70,"column":9},
    },
  ],
  model: {
    "services": [],
    "events": [],
    "objects": []
  },
}
