/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { TerminalCloseRequest, TerminalOpenRequest, TerminalOpenResult, TerminalReadRequest, TerminalReadResult, TerminalSignalRequest, TerminalWriteRequest } from '@deepseek-ai/dsh-host-terminal-bridge/types'
import type { SessionId } from '@deepseek-ai/dsh-session/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$7465726d696e616c5549 {
    close: (agentId: SessionId, request: TerminalCloseRequest) => Promise<RemoteResult<boolean>>
    open: (agentId: SessionId, request?: TerminalOpenRequest) => Promise<RemoteResult<TerminalOpenResult>>
    read: (agentId: SessionId, request: TerminalReadRequest) => Promise<RemoteResult<TerminalReadResult>>
    signal: (agentId: SessionId, request: TerminalSignalRequest) => Promise<RemoteResult<{ targetPgid: number; }>>
    write: (agentId: SessionId, request: TerminalWriteRequest) => Promise<RemoteResult<void>>
  }
  interface TypertRemoteMap {
    'terminalUI/close': (agentId: SessionId, request: TerminalCloseRequest) => Promise<RemoteResult<boolean>>
    'terminalUI/open': (agentId: SessionId, request?: TerminalOpenRequest) => Promise<RemoteResult<TerminalOpenResult>>
    'terminalUI/read': (agentId: SessionId, request: TerminalReadRequest) => Promise<RemoteResult<TerminalReadResult>>
    'terminalUI/signal': (agentId: SessionId, request: TerminalSignalRequest) => Promise<RemoteResult<{ targetPgid: number; }>>
    'terminalUI/write': (agentId: SessionId, request: TerminalWriteRequest) => Promise<RemoteResult<void>>
  }
  interface TypertRemoteNamespaceMap {
    'terminalUI': TypertRemoteNamespace$7465726d696e616c5549
  }
  interface TypertRemoteScopeMap {
    'agent:terminalUI/close': (request: TerminalCloseRequest) => Promise<RemoteResult<boolean>>
    'agent:terminalUI/open': (request?: TerminalOpenRequest) => Promise<RemoteResult<TerminalOpenResult>>
    'agent:terminalUI/read': (request: TerminalReadRequest) => Promise<RemoteResult<TerminalReadResult>>
    'agent:terminalUI/signal': (request: TerminalSignalRequest) => Promise<RemoteResult<{ targetPgid: number; }>>
    'agent:terminalUI/write': (request: TerminalWriteRequest) => Promise<RemoteResult<void>>
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
