/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { DirectoryListing, SystemMetricsSnapshot, SystemOverview } from '@deepseek-ai/dsh-host-system-metrics/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$73797374656d4d657472696373 {
    listDirectory: (path: string) => Promise<RemoteResult<DirectoryListing>>
    overview: () => Promise<RemoteResult<SystemOverview>>
    snapshot: () => Promise<RemoteResult<SystemMetricsSnapshot>>
  }
  interface TypertRemoteMap {
    'systemMetrics/listDirectory': (path: string) => Promise<RemoteResult<DirectoryListing>>
    'systemMetrics/overview': () => Promise<RemoteResult<SystemOverview>>
    'systemMetrics/snapshot': () => Promise<RemoteResult<SystemMetricsSnapshot>>
  }
  interface TypertRemoteNamespaceMap {
    'systemMetrics': TypertRemoteNamespace$73797374656d4d657472696373
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
